/*  Project Artest
    
    Copyright © 1994. All Rights Reserved.

    SUBSYSTEM:    artest.exe Application
    FILE:         artstedv.cpp
    AUTHOR:       


    OVERVIEW
    ========
    Source file for implementation of ArtestEditView (TEditView).      
*/


#include <owl\owlpch.h>
#pragma hdrstop

#include "artstapp.h"
#include "artstedv.h"

#include <stdio.h>


//{{ArtestEditView Implementation}}


//////////////////////////////////////////////////////////
// ArtestEditView
// ==========
// Construction/Destruction handling.
ArtestEditView::ArtestEditView (TDocument& doc, TWindow* parent)
    : TEditView(doc, parent)
{
    // INSERT>> Your constructor code here.

}


ArtestEditView::~ArtestEditView ()
{
    // INSERT>> Your destructor code here.

}
