$load baseq2/gfx/textures/episode1/base/keydr01.lbm
$mip    keydr1_1         16      16      128     128

$load baseq2/gfx/textures/episode1/base/keydr01.lbm
$mip    keydran1_1         16      16      128     128 anim keydran2_1
$mip    keydran2_1         152      16      128     128 anim keydran1_1

$load baseq2/gfx/textures/episode1/prison/keys.lbm
$mip    keysign1         16      16      32     32
$mip    keysign2         48      16      32     32

$load baseq2/gfx/textures/episode1/base/current.lbm
$mip	current1           16      16      64      64  water light 100 warping
$mip	current2           88      16      64      64  water light 100 warping

$load baseq2/gfx/textures/episode1/base/yellow.lbm
$mip	yellow1_1           16      16      64      32 
$mip	yellow1_2           88      16      64      32 
$mip	yellow1_3           16      56      64      16 
$mip	yellow1_4           88      56      64      16 
$mip	yellow1_5           16      80      32      16 
$mip	yellow1_6           88      80      32      16 

$load baseq2/gfx/textures/episode1/base/turret01.lbm
$mip	turret1_1           16      16      128      32 
$mip	turret2_1           16      56      128      32 
$mip	turret3_1           152     16      64       32 
$mip	turret4_1           224     16      64       32 
$mip	turret5_1           152     56      64       32 
$mip	turret6_1           224     56      32       32 
$mip	turret7_1           16      96      64       32
$mip	turret8_1           152     96      64       64
$mip	turret9_1           224     96      64       64 
 
$load baseq2/gfx/textures/episode1/base/red.lbm
$mip	reds1_1           16      16      64      32 
$mip	reds1_2           88      16      64      32 
$mip	reds1_3           16      56      64      16 
$mip	reds1_4           88      56      64      16 
$mip	reds1_5           16      80      32      16 
$mip	reds1_6           88      80      32      16 

$load baseq2/gfx/textures/episode1/base/caution.lbm
$mip	caution1_1           16      16      32      128 
$mip	caution1_2           56      16      32      128
$mip	caution1_3           96      16      32      128

$load baseq2/gfx/textures/episode1/base/window1.lbm
$mip	wndow0_1           16      16      64      64 window trans33
$mip	wndow0_2           16      88      64      64 window trans33
$mip	wndow0_3           88      16      128     128 window trans33

$load baseq2/gfx/textures/episode1/base/brokenfl.lbm
$mip	broken1_1           16      16      64      16 

$load baseq2/gfx/textures/episode2/refinery/floor1.lbm
$mip    doorbot         88              16              64              64

$load baseq2/gfx/textures/episode1/base/side.lbm
$mip	broken2_1           16      16      64      16 
$mip	broken2_2           88      16      64      16 
$mip	broken2_3           160     16      64      32 
$mip	broken2_4           232     16      64      32 

$load baseq2/gfx/textures/episode1/base/window.lbm
$mip	wndow1_1           16      16      64      64 window trans33
$mip	wndow1_2           88      16      64      64 window trans33
$mip	wndow1_3           160     16      64      64 window trans33
$mip	wndow1_4           232     16      64      64 window trans33
$mip	wndow1_5           16      88      64      64 window trans33
$mip	wndow1_6           88      88      64      64 window trans33
$mip	wndow1_7           160     88      64      64 window trans33
$mip	wndow1_8           232     88      64      64 window trans33

$load baseq2/gfx/textures/episode3/hangar/h_buton1.lbm
$mip	hbut1_1           16      16      16      16 anim hbut1_2
$mip	hbut1_2           40      16      16      16 anim hbut1_1

$load baseq2/gfx/textures/episode1/temp/ceiling1.lbm
$mip	ceil1_1           16      16      16      16      light   10000
$mip	ceil1_2           40      16      16      16      light   10000
$mip	ceil1_3           64      16      16      16      light   10000
$mip	ceil1_4           88      16      16      16      light   10000
$mip	ceil1_5           112     16      16      16      light   10000
$mip	ceil1_6           136     16      16      16      light   10000
$mip	ceil1_7           160     16      16      16      light   10000
$mip	ceil1_8           184     16      16      16      light   10000
$mip	ceil1_11           16      40      16      16      light   10000
$mip	ceil1_12           40      40      16      16      light   10000
$mip	ceil1_13           64      40      16      16      light   10000
$mip	ceil1_14           88      40      16      16      light   10000
$mip	ceil1_15           112     40      16      16      light   10000
$mip	ceil1_16           136     40      16      16      light   10000
$mip	ceil1_17           160     40      16      16      light   10000
$mip	ceil1_18           184     40      16      16      light   10000
$mip	ceil1_21           16      64      16      16      light   10000
$mip	ceil1_22           40      64      16      16      light   10000
$mip	ceil1_23           64      64      16      16      light   10000
$mip	ceil1_24           88      64      16      16      light   10000
$mip	ceil1_25           112     64      16      16      light   10000
$mip	ceil1_26           136     64      16      16      light   10000
$mip	ceil1_27           160     64      16      16      light   10000
$mip	ceil1_28           184     64      16      16      light   10000



$load baseq2/gfx/textures/episode1/base/p_sewer06.lbm
$mip	brwater           16      16      64      64     water light 100 warping

$load baseq2/gfx/textures/episode1/temp/current.lbm
$mip	cur_90            16      16      64      64     water light 100 warping
$mip	cur_0             88      16      64      64     water light 100 warping
$mip	cur_270           160     16      64      64     water light 100 warping
$mip	cur_180           232     16      64      64     water light 100 warping
$mip	cur_up            16      88      64      64     water light 100 warping
$mip	cur_dwn           88      88      64      64     water light 100 warping

$load baseq2/gfx/textures/episode1/temp/light01.lbm
$mip	tlight03          120     16      32      64 light 2500
$mip	tlight04          160     16      32      64 light 2500
$mip	tlight05          120     88      32      64 light 1500
$mip	tlight06          160     88      32      64 light 1500

$load baseq2/gfx/textures/episode1/base/water.lbm
$mip    water1         16     16      64      64 water light 100 warping trans33
$mip    water2         88     16      64      64 water light 100 warping trans33
$mip    bluwter        160    16      64      64 water light 100 warping trans33
$mip 	  water4	     232	16	  64	    64 water light 100 warping trans33
$mip    water5         16     88      64      64 water light 100 warping trans33
$mip    water6         88     88      64      64 water light 100 warping trans33
$mip    water7         160    88      64      64 water light 100 warping trans33
$mip    water8         232    88      64      64 water light 100 warping trans33


$load baseq2/gfx/textures/episode1/temp/nuke.lbm
$mip	winwater1                16              16      64      64      water light 100 window warping


$load baseq2/gfx/textures/ep_suprt/brn_metl.lbm
$mip	support1_1                16              16              32              128
$mip	support1_2                56              16              32              128             
$mip	support1_3                96              16              32              128

$load baseq2/gfx/textures/episode2/refinery/lava.lbm
$mip	lava     16      16      64      64      lava light 300 warping

$load baseq2/gfx/textures/episode2/refinery/lava.lbm
$mip	brlava		16      16      64      64    lava light 700 warping

$load baseq2/gfx/textures/ep_suprt/trigger.lbm
$mip	clip		16	16	32	32	nodraw playerclip monsterclip
$mip	clip_mon	56	16	32	32	nodraw monsterclip
$mip	hint		96	16	32	32	nodraw hint
$mip	skip		136	16	32	32	nodraw skip
$mip	trigger		176	16	32	32	nodraw
$mip	origin		216	16	32	32	nodraw origin
$mip	sky1		256	16	32	32	nodraw sky
$mip	sky2		256	16	32	32	nodraw sky
; no difference between sky1 and sky2, but some maps used the old different ones

$load baseq2/gfx/textures/episode2/refinery/shooter.lbm
$mip	shooter1          16              16              16              16
$mip	shooter2          40              16              16              16

$load baseq2/gfx/textures/episode2/waste/rock.lbm
$mip	rock0_1          16       16      128     128
$mip	rock0_2          152      16      128     128

$load baseq2/gfx/textures/episode2/mines/rocks12.lbm
$mip	rock12_1                 16       16      128     128
$mip	rock12_2                 152      16      128     128

$load baseq2/gfx/textures/episode2/mines/rocks25.lbm
$mip	rock25_1         16       16      256     128

$load baseq2/gfx/textures/episode2/mines/rocks13.lbm
$mip	rock13_1                 16       16      128     128
$mip	rock13_2                 152      16      128     128

$load baseq2/gfx/textures/episode2/mines/rocks14.lbm
$mip	rocks14_1         16      16      128     128
$mip	rocks14_2         152     16      128     128

$load baseq2/gfx/textures/episode2/mines/rocks15.lbm
$mip	rocks15_1         16      16      128     128
$mip	rocks15_2         152     16      128     128

$load baseq2/gfx/textures/episode2/mines/rocks16.lbm
$mip	rocks16_1         16      16      128     128
$mip	rocks16_2         152     16      128     128

$load baseq2/gfx/textures/episode2/mines/rocks18.lbm
$mip	rocks18_1         16      16      128     128

$load baseq2/gfx/textures/episode2/mines/rocks17.lbm
$mip	rocks17_1         16      16      128     128
$mip	rocks17_2         152     16      128     128

$load baseq2/gfx/textures/episode2/mines/rocks19.lbm
$mip	rocks19_1         16      16      256     128

$load baseq2/gfx/textures/episode2/mines/rocks20.lbm
$mip	rocks20_1         16      16      256     128

$load baseq2/gfx/textures/episode2/mines/rocks21.lbm
$mip	rocks21_1         16      16      256     128

$load baseq2/gfx/textures/episode2/mines/rocks22.lbm
$mip	rocks22_1         152      16      128     128

$load baseq2/gfx/textures/episode2/mines/rocks23.lbm
$mip	rocks23_2         16     16      256     128

$load baseq2/gfx/textures/episode2/mines/rocks24.lbm
$mip	rocks24_1         16      16      128     128
$mip	rocks24_2         152     16      128     128

$load baseq2/gfx/textures/episode2/refinery/grass.lbm
$mip	grass1_1           16      16      64      64
$mip	grass1_2           88      16      64      64
$mip	grass1_3           160     16      64      64
$mip	grass1_4           232     16      64      64
$mip	grass1_5           16      88      64      64
$mip	grass1_6           88      88      64      64
$mip	grass1_7           160     88      64      64
$mip	grass1_8           232     88      64      64

$load baseq2/gfx/textures/episode1/base/window4.lbm
$mip	window4_1				16		16		128		128		window
$mip	window4_2				152		16		128		128		window

$load baseq2/gfx/textures/episode1/base/window5.lbm
$mip	window5_1				16		16		128		128		window
$mip	brwind5_2				152		16		128		128		window


$load baseq2/gfx/textures/episode2/waste/pad.lbm
$mip	redkeypad           16      16      64      64
$mip	bluekeypad          88      16      64      64

;===
; Buttons
;===

$load baseq2/gfx/textures/episode1/base/basbut04.lbm
$mip	floorsw0           16      16      64      64 anim floorsw1  
$mip	floorsw1           88      16      64      64 anim floorsw2
$mip	floorsw2           160     16      64      64 anim floorsw3
$mip	floorsw3           232     16      64      64 anim floorsw0

$load baseq2/gfx/textures/episode1/base/basbut04.lbm
$mip	floorswno         16      16      64      64   
$mip	floorswno         160     16      64      64 

$load baseq2/gfx/textures/episode1/security/button01.lbm
$mip	+0btshoot1        56       16      32      32 anim +0btshoot2
$mip	+0btshoot2        56       48      32      32 anim +abtshoot2 
$mip	+abtshoot2        96       16      32      32 anim +abtshoot3
$mip	+abtshoot3        96       48      32      32 anim +0btshoot1
$mip	btf_on        	 136      16      64      64

$load baseq2/gfx/textures/episode1/security/button01.lbm
$mip	btf_off          136      16      64      64

$load baseq2/gfx/textures/episode2/mines/exit1.lbm
$mip	exit1           16      16      32      32

$load baseq2/gfx/textures/episode1/security/button01.lbm
$mip	butn01_1          16      16      32      32
$mip	+0butn1           208     56      32      16
$mip	+abutn2           248     56      32      16
$mip	+0butn4	    	16	  80	    32	48
$mip	+abutn5	    	56	  80	    32	48
$mip	+0butn6	    	16	  136	    32	48
$mip	+abutn7	    	56	  136	    32	48
$mip	+0butn8	    	96	  80	    32	32
$mip	+abutn8	    	136	  80	    32	32
$mip	+0butn9	    	96	  136	    32	32
$mip	+abutn9	    	136	  136	    32	32

$load baseq2/gfx/textures/episode2/waste/wastbut1.lbm
$mip	btactmach          104     16      32      32 
$mip	btactmach0         16      56      32      32 anim btactmach1
$mip	btactmach1         56      56      32      32 anim btactmach2
$mip	btactmach2         104     56      32      32 anim btactmach3
$mip	btactmach3         144     56      32      32 anim btactmach0
$mip	doorswt0         16      96      32      32 anim doorswt1
$mip	doorswt1         56      96      32      32 anim doorswt2
$mip	doorswt2         104     96      32      32 anim doorswt3
$mip	doorswt3         144     96      32      32 anim doorswt0
$mip	pyramid0         16      136      32      32 anim pyramid1
$mip	pyramid1         56      136      32      32 anim pyramid2
$mip	pyramid2         104     136      32      32 anim pyramid3
$mip	pyramid3         144     136      32      32 anim pyramid0

$load baseq2/gfx/textures/episode3/lab/buttons5.lbm
$mip	laserbut0         208      16      32      32 anim laserbut1
$mip	laserbut1         248      16      32      32 anim laserbut2
$mip	laserbut2         208     56      32      32 anim laserbut3
$mip	laserbut3         248     56      32      32 anim laserbut0
$mip	laserside         288     16      16      16

$load baseq2/gfx/textures/episode1/prison/p_button.lbm
$mip	btdoor_op         16      16      32      32 light 1000
$mip	btdoor_cl         56      16      32      32 light 1000
$mip	btdoor            96      16      32      32 light 1000
$mip	btmovmach         136     16      32      32 light 1000
$mip	btlaser           16      56      32      32 light 1000
$mip	btffield          56      56      32      32 light 1000
$mip	btwater           96      56      32      32 light 1000
$mip	btlight           136     56      32      32 light 1000
$mip	buttn1_0          176     56      32      32 light 1000
$mip	buttn1_a          216     56      32      32 light 1000
$mip	buttn1_b          256     56      32      32 light 1000

$load baseq2/gfx/textures/episode1/base/basbut01.lbm
$mip	btelev           16      128      32      32
$mip	face             216     16      32      32

$load baseq2/gfx/textures/episode1/base/basbut01.lbm
$mip	btelev_dn        16      16      32      32 anim btelev_dn3
$mip	btelev_dn2       16      80      32      32 anim btelev_dn4
$mip	btelev_dn3       56      16      32      32 anim btelev_dn
$mip	btelev_dn4       56      80      32      32 anim btelev_dn2

$load baseq2/gfx/textures/episode1/base/basbut01.lbm
$mip	btelev_up        16      16      32      32 anim btelev_up3
$mip	btelev_up2       16      80      32      32 anim btelev_up4
$mip	btelev_up3       96      16      32      32 anim btelev_up
$mip	btelev_up4       96      80      32      32 anim btelev_up2

$load baseq2/gfx/textures/episode1/base/basbut03.lbm
$mip	arrow0        16      16      32      32 anim arrow1
$mip	arrow1        16      80      32      32 anim arrow2
$mip	arrow2        56      16      32      32 anim arrow3
$mip	arrow3        56      80      32      32 anim arrow0
$mip	machine0        136      80      32      32 anim machine1
$mip	machine1        176      80      32      32 anim machine2
$mip	machine2        216      80      32      32 anim machine3
$mip	machine3        256      80      32      32 anim machine0

$load baseq2/gfx/textures/episode1/base/basbut03.lbm
$mip	arrowup0        16      16      32      32 anim arrowup1
$mip	arrowup1        16      80      32      32 anim arrowup2
$mip	arrowup2        96      16      32      32 anim arrowup3
$mip	arrowup3        96      80      32      32 anim arrowup0

$load baseq2/gfx/textures/episode1/base/lever.lbm
$mip	lever1        16      16      32      32 anim lever6
$mip	lever2        56      16      32      32 anim lever7
$mip	lever3        96      16      32      32 anim lever8
$mip	lever4        136     16      32      32 anim lever9
$mip	lever5        176     16      32      32 anim lever10
$mip	lever6        16      56      32      32 anim lever1
$mip	lever7        56      56      32      32 anim lever2
$mip	lever8        96      56      32      32 anim lever3
$mip	lever9        136     56      32      32 anim lever4
$mip	lever10       176     56      32      32 anim lever5

$load baseq2/gfx/textures/episode1/security/button01.lbm
$mip	dm_lt01_1          16      16      16      16

$load baseq2/gfx/textures/episode3/lab/buttons5.lbm
$mip	lbutt5_3          16       16      32      32
$mip	lbutt5_4          56       16      32      32
$mip	lbutt5_5          16       56      32      32
$mip	alarm0          128      16      32      32 anim alarm1
$mip	alarm1          168      16      32      32 anim alarm2
$mip	alarm2          128      56      32      32 anim alarm3
$mip	alarm3          168      56      32      32 anim alarm0

$load baseq2/gfx/textures/episode2/refinery/floor2.lbm
$mip    yelfield          232	88	64	64	window trans33 warping flowing

$load baseq2/gfx/textures/episode2/mines/c_met10.lbm
$mip    redfield          16      16      64     64	window trans33 warping flowing
