/*
	log_scr.c
	generated by Look & Feel version 3.2 from winx
	03/24/92
*/

#include <stdio.h>
#include "cscape.h"
#include "teddecl.h"
#include "msys.h"
#include "sled.h"

int log_scr(log_line1, log_line2, log_line3, log_line4, log_line5, log_line6, log_line7)
	char *log_line1;
	char *log_line2;
	char *log_line3;
	char *log_line4;
	char *log_line5;
	char *log_line6;
	char *log_line7;
{
	menu_type	menu;
	sed_type	sed;
	int 		ret;

	menu = menu_Open();

	menu_Printf(menu, "@p[0,0]@f{log_line1}p[@[49,#]]",
	  log_line1, &string_funcs);
	menu_Printf(menu, "@p[1,0]@f{log_line2}p[@[49,#] ]",
	  log_line2, &string_funcs);
	menu_Printf(menu, "@p[2,0]@f{log_line3}p[@[49,#] ]",
	  log_line3, &string_funcs);
	menu_Printf(menu, "@p[3,0]@f{log_line4}p[@[49,#] ]",
	  log_line4, &string_funcs);
	menu_Printf(menu, "@p[4,0]@f{log_line5}p[@[49,#] ]",
	  log_line5, &string_funcs);
	menu_Printf(menu, "@p[5,0]@f{log_line6}p[@[49,#] ]",
	  log_line6, &string_funcs);
	menu_Printf(menu, "@p[6,0]@f{log_line7}p[@[49,#] ]",
	  log_line7, &string_funcs);

	menu_Flush(menu);

	sed = sed_Open(menu);
	sed_SetColors(sed, 0x07, 0x07, 0x70);

	sed_MarkField(sed, 0, 0x07, 0x70);
	sed_SetBorder(sed, bd_prompt);
	sed_SetBorderTitle(sed, "Log");
	sed_SetBorderFeature(sed, BD_MOVE | BD_RESIZE | BD_OUTLINE);
	sed_SetPosition(sed, 9, 14);
	sed_SetHeight(sed, 7);
	sed_SetWidth(sed, 50);
	sed_SetShadow(sed, 1);
	sed_SetMouse(sed, sedmou_Click);

	sed_Repaint(sed);
	ret = sed_Go(sed);

	sed_Close(sed);
	return(ret);
}
