/*
	proc1.c
	generated by Look & Feel version 3.2 from proc1.lnf
	03/31/92
*/

#include <stdio.h>
#include "cscape.h"
#include "teddecl.h"
#include "msys.h"
#include "sled.h"

int proc1(addr1, 
          addr2, 
          addr3, 
          addr4, 
          addr5, 
          addr6, 
          pos, 
          reg_a, 
          reg_b, 
          reg_c, 
          reg_d, 
          reg_ip, 
          reg_tar, 
          next_address,
          prev_address,
          ss,
          end,
          last_cmd )
	int *addr1;
	int *addr2;
	int *addr3;
	int *addr4;
	int *addr5;
	int *addr6;
	int  *pos;
	int *reg_a;
	int *reg_b;
	int *reg_c;
	int *reg_d;
	int *reg_ip;
	int *reg_tar;
	char *next_address;
	char *prev_address;
	char *ss ;
	char *end;
  char *last_cmd;
{
	menu_type	menu;
	sed_type	sed;
	int 		ret;

	menu = menu_Open();

	menu_Printf(menu, "@[45, ]Registers\n    :@[38, ]A:\n    :@[38, ]B:\n    :@[38, ]C:\n    :@[38, ]D:\n    :");
	menu_Printf(menu, "@[37, ]IP:\n    :@[36, ]TAR:");
	menu_Printf(menu, "@p[1,0]@f{addr1}p[### ]",
	  addr1, &sint_funcs);
	menu_Printf(menu, "@p[2,0]@f{addr2}p[### ]",
	  addr2, &sint_funcs);
	menu_Printf(menu, "@p[3,0]@f{addr3}p[### ]",
	  addr3, &sint_funcs);
	menu_Printf(menu, "@p[4,0]@f{addr4}p[### ]",
	  addr4, &sint_funcs);
	menu_Printf(menu, "@p[5,0]@f{addr5}p[### ]",
	  addr5, &sint_funcs);
	menu_Printf(menu, "@p[6,0]@f{addr6}p[### ]",
	  addr6, &sint_funcs);
	menu_Printf(menu, "@p[1,7]@f{pos00}[## ]",
	  &(pos[0]), &sint_funcs);
	menu_Printf(menu, "@p[1,10]@f{pos01}[## ]",
	  &(pos[01]), &sint_funcs);
	menu_Printf(menu, "@p[1,13]@f{pos02}[## ]",
	  &(pos[02]), &sint_funcs);
	menu_Printf(menu, "@p[1,16]@f{pos03}[## ]",
	  &(pos[03]), &sint_funcs);
	menu_Printf(menu, "@p[1,19]@f{pos04}[## ]",
	  &(pos[04]), &sint_funcs);
	menu_Printf(menu, "@p[1,22]@f{pos05}[## ]",
	  &(pos[05]), &sint_funcs);
	menu_Printf(menu, "@p[1,25]@f{pos06}[## ]",
	  &(pos[06]), &sint_funcs);
	menu_Printf(menu, "@p[1,28]@f{pos07}[## ]",
	  &(pos[07]), &sint_funcs);
	menu_Printf(menu, "@p[1,31]@f{pos08}[## ]",
	  &(pos[8]), &sint_funcs);
	menu_Printf(menu, "@p[1,34]@f{pos09}[## ]",
	  &(pos[9]), &sint_funcs);
	menu_Printf(menu, "@p[2,7]@f{pos10}[## ]",
	  &(pos[10]), &sint_funcs);
	menu_Printf(menu, "@p[2,10]@f{pos11}[## ]",
	  &(pos[11]), &sint_funcs);
	menu_Printf(menu, "@p[2,13]@f{pos12}[## ]",
	  &(pos[12]), &sint_funcs);
	menu_Printf(menu, "@p[2,16]@f{pos13}[## ]",
	  &(pos[13]), &sint_funcs);
	menu_Printf(menu, "@p[2,19]@f{pos14}[## ]",
	  &(pos[14]), &sint_funcs);
	menu_Printf(menu, "@p[2,22]@f{pos15}[## ]",
	  &(pos[15]), &sint_funcs);
	menu_Printf(menu, "@p[2,25]@f{pos16}[## ]",
	  &(pos[16]), &sint_funcs);
	menu_Printf(menu, "@p[2,28]@f{pos17}[## ]",
	  &(pos[17]), &sint_funcs);
	menu_Printf(menu, "@p[2,31]@f{pos18}[## ]",
	  &(pos[18]), &sint_funcs);
	menu_Printf(menu, "@p[2,34]@f{pos19}[## ]",
	  &(pos[19]), &sint_funcs);
	menu_Printf(menu, "@p[3,7]@f{pos20}[## ]",
	  &(pos[20]), &sint_funcs);
	menu_Printf(menu, "@p[3,10]@f{pos21}[## ]",
	  &(pos[21]), &sint_funcs);
	menu_Printf(menu, "@p[3,13]@f{pos22}[## ]",
	  &(pos[22]), &sint_funcs);
	menu_Printf(menu, "@p[3,16]@f{pos23}[## ]",
	  &(pos[23]), &sint_funcs);
	menu_Printf(menu, "@p[3,19]@f{pos24}[## ]",
	  &(pos[24]), &sint_funcs);
	menu_Printf(menu, "@p[3,22]@f{pos25}[## ]",
	  &(pos[25]), &sint_funcs);
	menu_Printf(menu, "@p[3,25]@f{pos26}[## ]",
	  &(pos[26]), &sint_funcs);
	menu_Printf(menu, "@p[3,28]@f{pos27}[## ]",
	  &(pos[27]), &sint_funcs);
	menu_Printf(menu, "@p[3,31]@f{pos28}[## ]",
	  &(pos[28]), &sint_funcs);
	menu_Printf(menu, "@p[3,34]@f{pos29}[## ]",
	  &(pos[29]), &sint_funcs);
	menu_Printf(menu, "@p[4,7]@f{pos30}[## ]",
	  &(pos[30]), &sint_funcs);
	menu_Printf(menu, "@p[4,10]@f{pos31}[## ]",
	  &(pos[31]), &sint_funcs);
	menu_Printf(menu, "@p[4,13]@f{pos32}[## ]",
	  &(pos[32]), &sint_funcs);
	menu_Printf(menu, "@p[4,16]@f{pos33}[## ]",
	  &(pos[33]), &sint_funcs);
	menu_Printf(menu, "@p[4,19]@f{pos34}[## ]",
	  &(pos[34]), &sint_funcs);
	menu_Printf(menu, "@p[4,22]@f{pos35}[## ]",
	  &(pos[35]), &sint_funcs);
	menu_Printf(menu, "@p[4,25]@f{pos36}[## ]",
	  &(pos[36]), &sint_funcs);
	menu_Printf(menu, "@p[4,28]@f{pos37}[## ]",
	  &(pos[37]), &sint_funcs);
	menu_Printf(menu, "@p[4,31]@f{pos38}[## ]",
	  &(pos[38]), &sint_funcs);
	menu_Printf(menu, "@p[4,34]@f{pos39}[## ]",
	  &(pos[39]), &sint_funcs);
	menu_Printf(menu, "@p[5,7]@f{pos40}[## ]",
	  &(pos[40]), &sint_funcs);
	menu_Printf(menu, "@p[5,10]@f{pos41}[## ]",
	  &(pos[41]), &sint_funcs);
	menu_Printf(menu, "@p[5,13]@f{pos42}[## ]",
	  &(pos[42]), &sint_funcs);
	menu_Printf(menu, "@p[5,16]@f{pos43}[## ]",
	  &(pos[43]), &sint_funcs);
	menu_Printf(menu, "@p[5,19]@f{pos44}[## ]",
	  &(pos[44]), &sint_funcs);
	menu_Printf(menu, "@p[5,22]@f{pos45}[## ]",
	  &(pos[45]), &sint_funcs);
	menu_Printf(menu, "@p[5,25]@f{pos46}[## ]",
	  &(pos[46]), &sint_funcs);
	menu_Printf(menu, "@p[5,28]@f{pos47}[## ]",
	  &(pos[47]), &sint_funcs);
	menu_Printf(menu, "@p[5,31]@f{pos48}[## ]",
	  &(pos[48]), &sint_funcs);
	menu_Printf(menu, "@p[5,34]@f{pos49}[## ]",
	  &(pos[49]), &sint_funcs);
	menu_Printf(menu, "@p[6,7]@f{pos50}[## ]",
	  &(pos[50]), &sint_funcs);
	menu_Printf(menu, "@p[6,10]@f{pos51}[## ]",
	  &(pos[51]), &sint_funcs);
	menu_Printf(menu, "@p[6,13]@f{pos52}[## ]",
	  &(pos[52]), &sint_funcs);
	menu_Printf(menu, "@p[6,16]@f{pos53}[## ]",
	  &(pos[53]), &sint_funcs);
	menu_Printf(menu, "@p[6,19]@f{pos54}[## ]",
	  &(pos[54]), &sint_funcs);
	menu_Printf(menu, "@p[6,22]@f{pos55}[## ]",
	  &(pos[55]), &sint_funcs);
	menu_Printf(menu, "@p[6,25]@f{pos56}[## ]",
	  &(pos[56]), &sint_funcs);
	menu_Printf(menu, "@p[6,28]@f{pos57}[## ]",
	  &(pos[57]), &sint_funcs);
	menu_Printf(menu, "@p[6,31]@f{pos58}[## ]",
	  &(pos[58]), &sint_funcs);
	menu_Printf(menu, "@p[6,34]@f{pos59}[## ]",
	  &(pos[59]), &sint_funcs);
	menu_Printf(menu, "@p[1,46]@f{reg_a}p[##### ]",
	  reg_a, &int_funcs);
	menu_Printf(menu, "@p[2,46]@f{reg_b}p[##### ]",
	  reg_b, &int_funcs);
	menu_Printf(menu, "@p[3,46]@f{reg_c}p[##### ]",
	  reg_c, &int_funcs);
	menu_Printf(menu, "@p[4,46]@f{reg_d}p[##### ]",
	  reg_d, &int_funcs);
	menu_Printf(menu, "@p[5,46]@f{reg_ip}p[##### ]",
	  reg_ip, &int_funcs);
	menu_Printf(menu, "@p[6,46]@f{reg_tar}p[##### ]",
	  reg_tar, &int_funcs);
  menu_Printf(menu, "@p[7,46]@fp[########################################]",
    last_cmd, &string_funcs);
	menu_Printf(menu, "@p[8,7]@fd2[Page Down]",
	  next_address, &gmenu_funcs,NULL,"200");
	menu_Printf(menu, "@p[8,18]@fd2[Page Up]",
	  prev_address, &gmenu_funcs,NULL,"201");
	menu_Printf(menu, "@p[8,27]@fd2[Single Step]",
	  ss, &gmenu_funcs,NULL,"202");
	menu_Printf(menu, "@p[10,7]@fd2[End]",
	  end, &gmenu_funcs,NULL,"202");
	menu_Flush(menu);

	sed = sed_Open(menu);
	sed_SetColors(sed, 0x07, 0x07, 0x70);

	sed_SetBorder(sed, bd_prompt);
	sed_SetBorderTitle(sed, "Processor Window");
	sed_SetPosition(sed, 5, 12);
	sed_SetHeight(sed, 13);
	sed_SetWidth(sed, 55);

	sed_Repaint(sed);
	ret = sed_Go(sed);

	sed_Close(sed);
	return(ret);
}
