/*
	sops1.c
	generated by Look & Feel version 3.2 from sops.lnf
	03/31/92
*/

#include <stdio.h>
#include "cscape.h"
#include "teddecl.h"
#include "msys.h"
#include "sled.h"

int sops1(network, netbios, virus, printq)
	boolean *network;
	boolean *netbios;
	boolean *virus;
	boolean *printq;
{
	menu_type	menu;
	sed_type	sed;
	int 		ret;

	menu = menu_Open();

	menu_Printf(menu, "\n  Network:     @a[0x13]\n@a[0x00]  NetBios:     @a[0x13]\n@a[0x00]  Virus  :\n  PrintQ :\n\n  Use Up/Down Arrows to select\n  Space Bar to change\n  Return to Q");
	menu_Printf(menu, "uit");

	menu_Printf(menu, "@p[1,11]@f{network}[### ]",
	  network, &yesno_funcs);
	menu_Printf(menu, "@p[2,11]@f{netbios}[### ]",
	  netbios, &yesno_funcs);
	menu_Printf(menu, "@p[3,11]@f{virus}[### ]",
	  virus, &yesno_funcs);
	menu_Printf(menu, "@p[4,11]@f{printq}[### ]",
	  printq, &yesno_funcs);

	menu_Flush(menu);

	sed = sed_Open(menu);
	sed_SetColors(sed, 0x07, 0x1a, 0x70);

	sed_MarkField(sed, 0, 0x13, 0x1a);
	sed_MarkField(sed, 1, 0x13, 0x1a);
	sed_MarkField(sed, 2, 0x13, 0x1a);
	sed_MarkField(sed, 3, 0x13, 0x1a);
	sed_SetBorder(sed, bd_title);
	sed_SetBorderColor(sed, 0x07);
	sed_SetBorderTitle(sed, "Dos Environment Variables");
	sed_SetPosition(sed, 4, 22);
	sed_SetHeight(sed, 9);
	sed_SetWidth(sed, 34);
	sed_SetExplode(sed, exp_BeamMeUp);

	sed_Repaint(sed);
	ret = sed_Go(sed);

	sed_Close(sed);
	return(ret);
}
