#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3623
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqTest
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="CodeCrossRef")]
	public partial class CodeRefDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCodeCrossRef(CodeCrossRef instance);
    partial void UpdateCodeCrossRef(CodeCrossRef instance);
    partial void DeleteCodeCrossRef(CodeCrossRef instance);
    #endregion
		
		public CodeRefDataContext() : 
				base(global::LinqTest.Properties.Settings.Default.CodeCrossRefConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CodeRefDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CodeRefDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CodeRefDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CodeRefDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CodeCrossRef> CodeCrossRefs
		{
			get
			{
				return this.GetTable<CodeCrossRef>();
			}
		}
	}
	
	[Table(Name="dbo.CodeCrossRef")]
	public partial class CodeCrossRef : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CodeExample;
		
		private string _Description;
		
		private int _LanguageID;
		
		private int _CodeExampleID;
		
		private string _CodeExampleName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeExampleChanging(string value);
    partial void OnCodeExampleChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnLanguageIDChanging(int value);
    partial void OnLanguageIDChanged();
    partial void OnCodeExampleIDChanging(int value);
    partial void OnCodeExampleIDChanged();
    partial void OnCodeExampleNameChanging(string value);
    partial void OnCodeExampleNameChanged();
    #endregion
		
		public CodeCrossRef()
		{
			OnCreated();
		}
		
		[Column(Storage="_CodeExample", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string CodeExample
		{
			get
			{
				return this._CodeExample;
			}
			set
			{
				if ((this._CodeExample != value))
				{
					this.OnCodeExampleChanging(value);
					this.SendPropertyChanging();
					this._CodeExample = value;
					this.SendPropertyChanged("CodeExample");
					this.OnCodeExampleChanged();
				}
			}
		}
		
		[Column(Storage="_Description", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[Column(Storage="_LanguageID", DbType="Int NOT NULL")]
		public int LanguageID
		{
			get
			{
				return this._LanguageID;
			}
			set
			{
				if ((this._LanguageID != value))
				{
					this.OnLanguageIDChanging(value);
					this.SendPropertyChanging();
					this._LanguageID = value;
					this.SendPropertyChanged("LanguageID");
					this.OnLanguageIDChanged();
				}
			}
		}
		
		[Column(Storage="_CodeExampleID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CodeExampleID
		{
			get
			{
				return this._CodeExampleID;
			}
			set
			{
				if ((this._CodeExampleID != value))
				{
					this.OnCodeExampleIDChanging(value);
					this.SendPropertyChanging();
					this._CodeExampleID = value;
					this.SendPropertyChanged("CodeExampleID");
					this.OnCodeExampleIDChanged();
				}
			}
		}
		
		[Column(Storage="_CodeExampleName", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string CodeExampleName
		{
			get
			{
				return this._CodeExampleName;
			}
			set
			{
				if ((this._CodeExampleName != value))
				{
					this.OnCodeExampleNameChanging(value);
					this.SendPropertyChanging();
					this._CodeExampleName = value;
					this.SendPropertyChanged("CodeExampleName");
					this.OnCodeExampleNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
