//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by mfctree.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_MFCTRETYPE                  129
#define IDB_BELLEVUE                    130
#define IDB_FORSALE                     131
#define IDB_REDMOND                     132
#define IDB_SEATTLE                     133
#define IDR_MAINFRM                     134
#define IDI_BELLEVUE                    135
#define IDI_REDMOND                     136
#define IDI_SEATTLE                     137
#define IDI_FORSALE                     139

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        140
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
