// character constants

'\a'     // audible bell      0x07 BEL
'\b'     // backspace         0x08 BS
'\f'     // form feed         0x0C FF
'\n'     // newline           0x0A LF
'\r'     // carraige return   0x0D CR 
'\t'     // tab               0x09 HT
'\v'     // vertical tab      0x0B VT
'\\'     // a back slash
'\''     // a single quote
'\"'     // a double quote
'\?'     // a question mark
'\nnn'   // an Octal constanct (nnn is an octal number)
'\xnnn'  // a hexidecimal constant (nnn is a hex number)
'\Xnnn'  // a hexidecimal constant (nnn is a hex number)
