//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallTestService.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MonitoredItemValue", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary1")]
    [System.SerializableAttribute()]
    public partial struct MonitoredItemValue : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemIdentity_ContextNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ulong ItemIdentity_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemIdentity_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ushort ItemIdentity_ReferenceTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ushort ItemIdentity_TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private uint RuntimeValue_QualityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RuntimeValue_TimestampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RuntimeValue_Variant_LengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] RuntimeValue_Variant_PayloadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ushort RuntimeValue_Variant_TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Variant_LengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] Variant_PayloadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ushort Variant_TypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemIdentity_ContextName {
            get {
                return this.ItemIdentity_ContextNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemIdentity_ContextNameField, value) != true)) {
                    this.ItemIdentity_ContextNameField = value;
                    this.RaisePropertyChanged("ItemIdentity_ContextName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ulong ItemIdentity_Id {
            get {
                return this.ItemIdentity_IdField;
            }
            set {
                if ((this.ItemIdentity_IdField.Equals(value) != true)) {
                    this.ItemIdentity_IdField = value;
                    this.RaisePropertyChanged("ItemIdentity_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemIdentity_Name {
            get {
                return this.ItemIdentity_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemIdentity_NameField, value) != true)) {
                    this.ItemIdentity_NameField = value;
                    this.RaisePropertyChanged("ItemIdentity_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ushort ItemIdentity_ReferenceType {
            get {
                return this.ItemIdentity_ReferenceTypeField;
            }
            set {
                if ((this.ItemIdentity_ReferenceTypeField.Equals(value) != true)) {
                    this.ItemIdentity_ReferenceTypeField = value;
                    this.RaisePropertyChanged("ItemIdentity_ReferenceType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ushort ItemIdentity_Type {
            get {
                return this.ItemIdentity_TypeField;
            }
            set {
                if ((this.ItemIdentity_TypeField.Equals(value) != true)) {
                    this.ItemIdentity_TypeField = value;
                    this.RaisePropertyChanged("ItemIdentity_Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint RuntimeValue_Quality {
            get {
                return this.RuntimeValue_QualityField;
            }
            set {
                if ((this.RuntimeValue_QualityField.Equals(value) != true)) {
                    this.RuntimeValue_QualityField = value;
                    this.RaisePropertyChanged("RuntimeValue_Quality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RuntimeValue_Timestamp {
            get {
                return this.RuntimeValue_TimestampField;
            }
            set {
                if ((this.RuntimeValue_TimestampField.Equals(value) != true)) {
                    this.RuntimeValue_TimestampField = value;
                    this.RaisePropertyChanged("RuntimeValue_Timestamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RuntimeValue_Variant_Length {
            get {
                return this.RuntimeValue_Variant_LengthField;
            }
            set {
                if ((this.RuntimeValue_Variant_LengthField.Equals(value) != true)) {
                    this.RuntimeValue_Variant_LengthField = value;
                    this.RaisePropertyChanged("RuntimeValue_Variant_Length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] RuntimeValue_Variant_Payload {
            get {
                return this.RuntimeValue_Variant_PayloadField;
            }
            set {
                if ((object.ReferenceEquals(this.RuntimeValue_Variant_PayloadField, value) != true)) {
                    this.RuntimeValue_Variant_PayloadField = value;
                    this.RaisePropertyChanged("RuntimeValue_Variant_Payload");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ushort RuntimeValue_Variant_Type {
            get {
                return this.RuntimeValue_Variant_TypeField;
            }
            set {
                if ((this.RuntimeValue_Variant_TypeField.Equals(value) != true)) {
                    this.RuntimeValue_Variant_TypeField = value;
                    this.RaisePropertyChanged("RuntimeValue_Variant_Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Variant_Length {
            get {
                return this.Variant_LengthField;
            }
            set {
                if ((this.Variant_LengthField.Equals(value) != true)) {
                    this.Variant_LengthField = value;
                    this.RaisePropertyChanged("Variant_Length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Variant_Payload {
            get {
                return this.Variant_PayloadField;
            }
            set {
                if ((object.ReferenceEquals(this.Variant_PayloadField, value) != true)) {
                    this.Variant_PayloadField = value;
                    this.RaisePropertyChanged("Variant_Payload");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ushort Variant_Type {
            get {
                return this.Variant_TypeField;
            }
            set {
                if ((this.Variant_TypeField.Equals(value) != true)) {
                    this.Variant_TypeField = value;
                    this.RaisePropertyChanged("Variant_Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        CallTestService.ServiceReference1.MonitoredItemValue[] GetData();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : CallTestService.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<CallTestService.ServiceReference1.IService1>, CallTestService.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CallTestService.ServiceReference1.MonitoredItemValue[] GetData() {
            return base.Channel.GetData();
        }
    }
}
