/* KEYS.H  -  Key definitions for routines using onein    */

/*  Function Keys
    =============  */

#define  F1    315
#define  F2    316
#define  F3    317
#define  F4    318
#define  F5    319
#define  F6    320
#define  F7    321
#define  F8    322
#define  F9    323
#define  F10   324

#define  SF1   340
#define  SF2   341
#define  SF3   342
#define  SF4   343
#define  SF5   344
#define  SF6   345
#define  SF7   346
#define  SF8   347
#define  SF9   348
#define  SF10  349

#define  CF1   350
#define  CF2   351
#define  CF3   352
#define  CF4   353
#define  CF5   354
#define  CF6   355
#define  CF7   356
#define  CF8   357
#define  CF9   358
#define  CF10  359

#define  AF1   360
#define  AF2   361
#define  AF3   362
#define  AF4   363
#define  AF5   364
#define  AF6   365
#define  AF7   366
#define  AF8   367
#define  AF9   368
#define  AF10  369


/* Special Keys
   ============ */

#define  INS   338
#define  DEL   339
#define  UP    328
#define  DOWN  336
#define  LEFT  331
#define  RIGHT 333
#define  PGUP  329
#define  PGDN  337
#define  HOME  327
#define  END   335

#define  CRIGHT  372
#define  CLEFT   371
#define  CPGUP   388
#define  CPGDN   374
#define  CRET    10
#define  CPRTSCRN 370
#define  CHOME   375
#define  CEND    373

#define   RET    13
#define   CR     13
#define   LF     10
#define   ESC    27
#define   BS     8

/*  ALT KEYS
    ========   */

#define  ALTA      286
#define  ALTB      304
#define  ALTC      302
#define  ALTD      288
#define  ALTE      274
#define  ALTF      289
#define  ALTG      290
#define  ALTH      291
#define  ALTI      279
#define  ALTJ      292
#define  ALTK      293
#define  ALTL      294
#define  ALTM      306
#define  ALTN      305
#define  ALTO      280
#define  ALTP      281
#define  ALTQ      272
#define  ALTR      275
#define  ALTS      287
#define  ALTT      276
#define  ALTU      278
#define  ALTV      303
#define  ALTW      273
#define  ALTX      301
#define  ALTY      277
#define  ALTZ      300
#define  ALT0      385
#define  ALT1      376
#define  ALT2      377
#define  ALT3      378
#define  ALT4      379
#define  ALT5      380
#define  ALT6      381
#define  ALT7      382
#define  ALT8      383
#define  ALT9      384
#define  ALTMINUS  386
#define  ALTEQ     387
