//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMManagerMock
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class XMLs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XMLs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TCPTesting.XMLs", typeof(XMLs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SMApplicationMessage TypeId=&quot;NetworkDeviceStateNotification&quot; ClientID=&quot;7592OLEKSIYZHUCK-PC&quot; Timestamp=&quot;2007-12-04T17:02:45.177-08:00&quot;&gt;
        ///  &lt;result code=&quot;0&quot;&gt;OK&lt;/result&gt;
        ///  &lt;wwandevicestate&gt;
        ///    &lt;state&gt;6&lt;/state&gt;
        ///    &lt;statedesc&gt;STATE_CONNECTED&lt;/statedesc&gt;
        ///    &lt;devicename&gt;Dell Wireless 5720 VZW Mobile Broadband (EVDO Rev-A) Minicard&lt;/devicename&gt;
        ///    &lt;ip&gt;&lt;/ip&gt;
        ///    &lt;ipv6&gt;&lt;/ipv6&gt;
        ///    &lt;dns1&gt;&lt;/dns1&gt;
        ///    &lt;dns2&gt;&lt;/dns2&gt;
        ///    &lt;metric&gt;1&lt;/metric&gt;
        ///    &lt;vpn&gt;false&lt;/vpn&gt;
        ///    &lt;domain&gt;Quick 2 Net (14.4kbps)&lt;/domain&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NetworkDeviceState {
            get {
                return ResourceManager.GetString("NetworkDeviceState", resourceCulture);
            }
        }
    }
}
